# Generated by Django 5.1.3 on 2024-11-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Desconocido', 'Desconocido')], max_length=15)),
                ('saldo', models.IntegerField()),
                ('activo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('nivel_de_satisfaccion', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
            ],
        ),
    ]
